framework:
    html_sanitizer:
        sanitizers:
            default:
                allow_safe_elements: true
                allow_relative_medias: true
            app.experience_sanitizer:
                allow_elements:
                    p: []
                    ul: []
                    ol: []
                    li: []
                    strong: []
                    em: []
            app.legal_sanitizer:
                allow_elements:
                    h2: []
                    h3: []
                    h4: []
                    h5: []
                    h6: []
                    p: []
                    ul: []
                    ol: []
                    li: []
            app.page_text_sanitizer:
                allow_elements:
                    p: []
                    strong: []
                    em: []
