parameters:
    theme: light
    timezone: Europe/Paris
branding:
    site_title: 'Mon site'
    logo: null
    favicon_svg: null
    favicon_ico: null
    apple_touch_icon: null
structured_identity:
    type: ''
    name: null
    url: null
    same_as: {  }
    article_author: false
pages:
    homepage_id: 1
maintenance:
    enabled: false
    message: 'Le site est actuellement en maintenance.'
    links: {  }
