# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    page_upload_directory: '%kernel.project_dir%/public/uploads/pages'
    settings_upload_directory: '%kernel.project_dir%/public/uploads/settings'
    blog_upload_directory: '%kernel.project_dir%/public/uploads/blog'
    project_upload_directory: '%kernel.project_dir%/public/uploads/projects'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Application\Settings\Storage\YamlSettingsStorage:
        arguments:
            $settingsConfigurationFile: '%kernel.project_dir%/src/Config/config.yaml'

    App\Service\FileUploaderService:
        arguments:
            $targetDirectory: '%page_upload_directory%'

    App\Application\Settings\General\Asset\SiteAssetUploader:
        arguments:
            $targetDirectory: '%settings_upload_directory%'

    App\Application\Blog\Article\Asset\ArticleCoverImageUploader:
        arguments:
            $targetDirectory: '%blog_upload_directory%'

    App\Application\Project\Asset\ProjectImageUploader:
        arguments:
            $targetDirectory: '%project_upload_directory%'

    App\Application\Reservation\Appointment\Meeting\GoogleCalendarMeetingCreator:
        arguments:
            $clientId: '%env(GOOGLE_CALENDAR_CLIENT_ID)%'
            $clientSecret: '%env(GOOGLE_CALENDAR_CLIENT_SECRET)%'
            $refreshToken: '%env(GOOGLE_CALENDAR_REFRESH_TOKEN)%'
            $calendarId: '%env(GOOGLE_CALENDAR_ID)%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
